### ISSUE TITLE
Missing classification

### ISSUE THREAD

**Issue by shopify-services** [Shopify/javascript-utilities#3]
**Owners**: @Shopify/operational-excellence (This repo has no owners)
**Service**: [javascript-utilities/production](https://services.shopify.io/services/javascript-utilities/production)

Please set a classification.

You can add it in [service.yml](https://github.com/shopify/javascript-utilities/blob/master/service.yml), under the key `classification`.

Refer to the [detailed documentation](https://services.shopify.io/doc/classifying_services_in_tiers) for more information.

**Comment by jarthorn** [comment]
I suspect `library` is the right answer here.
