### ISSUE TITLE
[focus] FOCUSABLE_SELECTOR should exclude disabled buttons

### ISSUE THREAD

**Issue by chloerice** [Shopify/javascript-utilities#30]
Right now, `findFirstFocusableNode` and `findLastFocusableNode` will focus disabled nodes. This is problematic because it breaks tabbability. Take for example the Polaris `ActionList` component when the first list item is `disabled`:

![focusablenode](https://user-images.githubusercontent.com/18447883/33399047-1d27c630-d51f-11e7-81ed-c7da0a7ae2ff.gif)

By changing `const FOCUSABLE_SELECTOR = '...,button...'` 
to `const FOCUSABLE_SELECTOR = '...,button:not(:disabled)...'`

Tabbability remains intact and behavior is as expected:

![focusablenodenotdisabled](https://user-images.githubusercontent.com/18447883/33399055-224799ec-d51f-11e7-8d58-38daa6b13d02.gif)

I'm wondering if it makes sense to return a disabled node for any of the disableable selectors (a, input, select, textarea)? If not, when I make the PR I'll specify `:not(:disabled)` on those as well.

**Comment by svinkle** [comment]
`a` doesn't have a `disabled` attribute or state.

Could you just add `:not(:disabled)` and it'll target anything in a `disabled` state?
